# Generated by Django 3.0.14 on 2023-09-03 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_restaurant', '0003_remove_coupons_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupons',
            old_name='products',
            new_name='product',
        ),
    ]
