# Generated by Django 4.1.1 on 2023-02-06 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_restaurant', '0003_alter_cartitem_item_alter_cartitem_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
