# Generated by Django 4.1.1 on 2023-02-06 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_restaurant', '0004_cartitem_final_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='final_price',
        ),
    ]
