# Generated by Django 3.0.14 on 2023-09-03 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_restaurant', '0004_auto_20230903_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='applied_coupon_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='coupons',
            name='coupon_type',
            field=models.CharField(choices=[('fixed', 'Fixed Amount'), ('percentage', 'Percentage')], default='percentage', max_length=10),
        ),
        migrations.AddField(
            model_name='coupons',
            name='fixed_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='coupons',
            name='percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
