# Generated by Django 3.0.14 on 2023-09-03 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_restaurant', '0005_auto_20230903_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupons',
            name='product',
            field=models.CharField(default='null', max_length=40, null=True),
        ),
    ]
