# Generated by Django 4.1.1 on 2023-02-06 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_restaurant', '0005_remove_cartitem_final_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
