# Generated by Django 4.1.1 on 2023-02-06 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_restaurant', '0006_cartitem_final_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='amount_to_be_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
