# Generated by Django 3.0.14 on 2023-09-03 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_restaurant', '0006_auto_20230903_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='reduced_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
