# Generated by Django 4.2.5 on 2023-09-07 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_restaurant', '0008_profile_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='table',
            field=models.CharField(default='null', max_length=50),
        ),
    ]
