# Generated by Django 3.0.14 on 2023-09-06 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_restaurant', '0008_profile_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupons',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
