# Generated by Django 3.0.14 on 2023-09-17 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_restaurant', '0009_cart_table'),
        ('my_restaurant', '0009_coupons_user_id'),
    ]

    operations = [
    ]
