# Generated by Django 3.0.14 on 2023-10-05 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_restaurant', '0010_merge_20230917_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='taken',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Qr_code_reads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('ordered', models.BooleanField(default=0)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_restaurant.Table')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
