# Generated by Django 3.0.14 on 2023-10-05 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_restaurant', '0011_auto_20231005_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qr_code_reads',
            name='time',
        ),
        migrations.AddField(
            model_name='qr_code_reads',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
    ]
