# Generated by Django 3.0.14 on 2023-10-05 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_restaurant', '0012_auto_20231005_1624'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qr_code_reads',
            old_name='end_time',
            new_name='read_time',
        ),
    ]
