# Generated by Django 3.0.14 on 2023-03-19 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_restaurant', '0012_auto_20230319_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='user',
        ),
    ]
