# Generated by Django 3.0.14 on 2023-10-05 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_restaurant', '0013_auto_20231005_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='qr_code_reads',
            name='finalized',
            field=models.BooleanField(default=0),
        ),
    ]
