# Generated by Django 3.0.14 on 2023-10-08 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_restaurant', '0014_qr_code_reads_finalized'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='order_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
