# Generated by Django 4.2.6 on 2023-10-30 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_restaurant', '0015_cart_order_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='language',
            field=models.CharField(choices=[('en-us', 'English'), ('nl', 'Dutch')], default='en-us', max_length=5),
        ),
    ]
