# Generated by Django 4.2.6 on 2023-11-17 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_restaurant', '0016_profile_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='language',
            field=models.CharField(choices=[('en-us', 'English'), ('nl', 'Dutch'), ('hu', 'Hungarian')], default='hu', max_length=5),
        ),
    ]
