# Generated by Django 3.0.14 on 2023-04-14 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_restaurant', '0017_cart_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_ready',
            field=models.BooleanField(default=False),
        ),
    ]
