# Generated by Django 4.2.6 on 2023-12-12 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_restaurant', '0018_extra_menuitem_extras'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='extras',
            field=models.ManyToManyField(blank=True, to='my_restaurant.extra'),
        ),
        migrations.AddField(
            model_name='extra',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
