# Generated by Django 4.2.6 on 2023-12-12 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_restaurant', '0019_cartitem_extras_extra_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='extras',
        ),
    ]
