# Generated by Django 4.2.6 on 2023-12-12 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_restaurant', '0020_remove_cartitem_extras'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='extras',
            field=models.ManyToManyField(blank=True, to='my_restaurant.extra'),
        ),
    ]
