# Generated by Django 4.2.6 on 2024-01-03 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_restaurant', '0022_ingredient_menuitem_ingredients'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItemIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_restaurant.ingredient')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_restaurant.menuitem')),
            ],
        ),
    ]
