# Generated by Django 4.2.6 on 2024-01-07 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_restaurant', '0023_menuitemingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
